id: CVE-2025-49113

info:
  name: Roundcube <= 1.6.10 Post-Auth RCE via PHP Object Deserialization
  author: Ademking
  severity: critical
  description: |
    Roundcube Webmail before 1.5.10 and 1.6.x before 1.6.11 allows remote code execution by authenticated users because the _from parameter in a URL is not validated in program/actions/settings/upload.php, leading to PHP Object Deserialization.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2025-49113
    - https://github.com/advisories/GHSA-8j8w-wwqc-x596
    - https://fearsoff.org/research/roundcube
    - http://www.openwall.com/lists/oss-security/2025/06/02/3
    - https://roundcube.net/news/2025/06/01/security-updates-1.6.11-and-1.5.10
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:H
    cvss-score: 10
    cve-id: CVE-2025-49113
    cwe-id: CWE-502
  metadata:
    vendor: roundcube
    product: webmail
  tags: roundcube,portal,tech

http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        words:
         - 'Roundcube'
         - 'roundcube'
        condition: or
        part: body
      - type: regex
        regex:
          - '"rcversion":\d\d\d\d'
        condition: or
        part: body

    extractors:
      - type: regex
        name: major
        group: 1
        regex:
          - '"rcversion":(\d)'
        internal: true

      - type: regex
        name: minor
        group: 1
        regex:
          - '"rcversion":\d\d(\d)'
        internal: true

      - type: regex
        name: patch
        group: 1
        regex:
          - '"rcversion":\d\d\d(\d+)'
        internal: true

      - type: dsl
        name: version
        dsl:
          - 'major + "." + minor + "." + patch'
        internal: true

      - type: dsl
        name: vulnerable
        dsl:
          - "compare_versions(version, '< 1.5.10') || (compare_versions(version, '>= 1.6.0') && compare_versions(version, '< 1.6.11'))"
        internal: true

      - type: dsl
        dsl:
          - '"Version: " + version'
